# Site settings
title: Aseeker
SEOTitle: Yzx's blog
header-img: img/post-bg-desk.jpg
email: you.zx@foxmail.com
description: "Similing!"
keyword: "aseeker, cs"
url: "http://acatcher.github.io"          # your host, for absolute URL
baseurl: ""      # for example, '/blog' if your blog hosted on 'host/blog'
github_repo: "https://github.com/acatcher/acatcher.github.io.git" # you code repository

# Sidebar settings
sidebar: true                           # whether or not using Sidebar.
sidebar-about-description: "Enjoy Life!"
sidebar-avatar: /img/pic.jpg      # use absolute URL, seeing it's used in both `/` and `/about/`



# SNS settings
RSS: false
# weibo_username:     qiubaiying
#zhihu_username:     Yyyou
github_username:    acatcher
#facebook_username:  baiying.qiu.7
#jianshu_username:   e71990ada2fd
twitter_username:   Aseekering




# Build settings
# from 2016, 'pygments' is unsupported on GitHub Pages. Use 'rouge' for highlighting instead.
permalink: pretty
paginate: 10
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
anchorjs: true                          # if you want to customize anchor. check out line:181 of `post.html`



# Gems
# from PR#40, to support local preview for Jekyll 3.0
gems: [jekyll-paginate]




# Markdown settings
# replace redcarpet to kramdown,
# although redcarpet can auto highlight code, the lack of header-id make the catalog impossible, so I switch to kramdown
# document: http://jekyllrb.com/docs/configuration/#kramdown
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM                            # use Github Flavored Markdown !important



# 评论系统
# Disqus（https://disqus.com/）
# disqus_username: qiubaiying

# Gitalk
gitalk:
 enable: true    #是否开启Gitalk评论
 clientID: 4ba8ded231d9875d939e                            #生成的clientID
 clientSecret: e9aacb77788029196ed28d547369400a549199ff    #生成的clientSecret
 repo: acatcher.github.io    #仓库名称
 owner: acatcher    #github用户名
 admin: acatcher
 distractionFreeMode: true #是否启用类似FB的阴影遮罩

# comments: true

# comments:
#   gitalk: true
#   gitalk_clientID: '4ba8ded231d9875d939e'
#   gitalk_Secret: 'e9aacb77788029196ed28d547369400a549199ff'
#   gitalk_repo: 'acatcher.github.io'
#   gitalk_owner: 'acatcher'
#   gitalk_admin: 'acatcher'
#   distractionFreeMode: true



# 统计

# Analytics settings
# Baidu Analytics
ba_track_id: b50bf2b12b5338a1845e33832976fd68

# Google Analytics
ga_track_id: 'UA-135471882-1'            # Format: UA-xxxxxx-xx
ga_domain: aseeker.xyz               # 默认的是 auto, 这里我是自定义了的域名，你如果没有自己的域名，需要改成auto





# Featured Tags
featured-tags: true                     # 是否使用首页标签
featured-condition-size: 1              # 相同标签数量大于这个数，才会出现在首页



# Progressive Web Apps
chrome-tab-theme-color: "#000000"
service-worker: true



# Friends
friends: [
    {
        title: "google",
        href: "https://www.google.com"
    },{
        title: "bing",
        href: "https://cn.bing.com"
    },{
      title: "好朋友小明",
      href: "https://doctordo.cn"
    },
]
